# Generated by Django 3.1.2 on 2020-10-29 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('marca', models.CharField(max_length=25)),
                ('precio', models.FloatField()),
                ('stockmin', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField(default=0)),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.tipoproducto')),
            ],
        ),
    ]
